steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'eu.gcr.io/gcpdatapipeline-420609/terraform:1.8.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
        cd iaac
        terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'eu.gcr.io/gcpdatapipeline-420609/terraform:1.8.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
        cd iaac
        terraform plan

# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'eu.gcr.io/gcpdatapipeline-420609/terraform:1.8.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
        cd iaac
        terraform apply -auto-approve

# [END tf-apply]

